### ISSUE TITLE
connect coveralls.io

### ISSUE THREAD

**Issue by hugojosefson** [hugojosefson/color-hash#6]
## Blocked
waiting for `@std/esm#0.11.3`. See https://github.com/standard-things/esm/issues/117.

Or! Try with babel: See #1.

Or! It might work anyway thanks to `test/.mocharc.`

## TODO
- [ ] https://github.com/nickmerwin/node-coveralls#readme
- [ ] https://coveralls.io/github/hugojosefson/color-hash
- [ ] Add coverage shield to `README.md`

**Comment by jdalton** [comment]
`@std/esm` is up to v0.16.0 🎉
